apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend-tgb
  namespace: expense
spec:
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:344060441143:targetgroup/expense-dev-ingress/8b76809addea37d6
  serviceRef:
    name: frontend
    port: 80
  # targetType: ip
