kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: backend
    project: expense
    Deployment: blue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
