kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
    Deployment: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
      Deployment: blue
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
        Deployment: blue
    spec:
      containers:
      - name: nginx
        image: sivasaikumar943/backend:2.0.0
        envFrom:
        - configMapRef:
            name: backend