kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-green
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
    Deployment: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
      Deployment: green
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
        Deployment: green
    spec:
      containers:
      - name: nginx
        image: sivasaikumar943/backend:3.0.0
        envFrom:
        - configMapRef:
            name: backend